
"""Rate limiting backends for API protection."""

from __future__ import annotations

from collections import deque
from threading import Lock
from time import perf_counter, time
from typing import Protocol
from uuid import uuid4

from redis import Redis
from redis.exceptions import RedisError


class RateLimiter(Protocol):
    """Interface implemented by all supported rate limiter backends."""

    def allow(self, key: str, limit: int) -> bool:
        """Return whether key can perform another request in current time window."""

    def is_healthy(self) -> bool:
        """Return whether limiter backend can currently serve requests."""


class InMemoryRateLimiter:
    """Sliding-window limiter keyed by client identifier."""

    def __init__(self, window_seconds: int = 60) -> None:
        """Initialize limiter store for per-client request timestamps."""

        self._window_seconds = window_seconds
        self._store: dict[str, deque[float]] = {}
        self._lock = Lock()

    def allow(self, key: str, limit: int) -> bool:
        """Return whether key can perform another request in current time window."""

        if limit <= 0:
            return False

        now = perf_counter()
        with self._lock:
            queue = self._store.setdefault(key, deque())
            cutoff = now - self._window_seconds
            while queue and queue[0] < cutoff:
                queue.popleft()

            if len(queue) >= limit:
                return False

            queue.append(now)
        return True

    def is_healthy(self) -> bool:
        """Always return healthy for process-local in-memory backend."""

        return True


# Generated by GitHub Copilot
class RedisRateLimiter:
    """Distributed sliding-window limiter backed by Redis sorted sets."""

    _ALLOW_SCRIPT = """
local key = KEYS[1]
local now = tonumber(ARGV[1])
local window_ms = tonumber(ARGV[2])
local limit = tonumber(ARGV[3])
local member = ARGV[4]
local ttl_seconds = tonumber(ARGV[5])

redis.call('ZREMRANGEBYSCORE', key, 0, now - window_ms)
local count = redis.call('ZCARD', key)
if count >= limit then
  redis.call('EXPIRE', key, ttl_seconds)
  return 0
end

redis.call('ZADD', key, now, member)
redis.call('EXPIRE', key, ttl_seconds)
return 1
"""

    def __init__(
        self,
        redis_client: Redis,
        window_seconds: int = 60,
        key_prefix: str = "hallucination-lens:rate-limit",
    ) -> None:
        """Initialize distributed limiter with Redis client and key namespace."""

        self._redis = redis_client
        self._window_seconds = window_seconds
        self._window_ms = window_seconds * 1000
        self._ttl_seconds = max(window_seconds + 5, 6)
        self._key_prefix = key_prefix
        self._allow_script = self._redis.register_script(self._ALLOW_SCRIPT)

    @classmethod
    def from_url(
        cls,
        redis_url: str,
        *,
        window_seconds: int = 60,
        key_prefix: str = "hallucination-lens:rate-limit",
        socket_timeout_seconds: float = 1.0,
    ) -> "RedisRateLimiter":
        """Build limiter from Redis connection URL and validate connectivity."""

        client = Redis.from_url(
            redis_url,
            encoding="utf-8",
            decode_responses=True,
            socket_timeout=socket_timeout_seconds,
            socket_connect_timeout=socket_timeout_seconds,
        )
        limiter = cls(
            redis_client=client,
            window_seconds=window_seconds,
            key_prefix=key_prefix,
        )
        if not limiter.is_healthy():
            raise RuntimeError("Redis rate limiter is unavailable")
        return limiter

    def allow(self, key: str, limit: int) -> bool:
        """Return whether key can perform another request in current Redis window."""

        if limit <= 0:
            return False

        now_ms = int(time() * 1000)
        member = f"{now_ms}:{uuid4().hex}"
        namespaced_key = f"{self._key_prefix}:{key}"

        try:
            result = self._allow_script(
                keys=[namespaced_key],
                args=[now_ms, self._window_ms, limit, member, self._ttl_seconds],
            )
        except RedisError as exc:
            raise RuntimeError("Redis rate limiter is unavailable") from exc

        return int(result) == 1

    def is_healthy(self) -> bool:
        """Return whether Redis backend currently responds to health checks."""

        try:
            return bool(self._redis.ping())
        except RedisError:
            return False
